### ISSUE TITLE
please specify the license

### ISSUE THREAD

**Issue by willkg** [Pomax/RGBAnalyse#5]
This repository has no license information. What permissions do users have with this code?

The best thing to do is add a LICENSE or COPYING file.

http://choosealicense.com/

**Comment by Pomax** [comment]
MIT, I'll add it to the README

**Comment by Pomax** [comment]
also added to the main source file. Production build gets stripped of comments because that'd just be padding.

**Comment by Pomax** [comment]
in fact, public domain except in countries where pd is not recognised. MIT for those.
