### ISSUE TITLE
Document Node usage

### ISSUE THREAD

**Issue by rayshan** [Pomax/RGBAnalyse#7]
Hi. This package already can be used in node, as `RGBAnalyse.analyse` takes either an `HTMLCanvasElement` or a path as the first argument. May be a good idea to document this for new users.

**Comment by Pomax** [comment]
The fact that it can be installed using both bower (which is a client side package manager) and npm (the node package manager) should be enough of a signal there?

**Comment by rayshan** [comment]
I think it'll be nice to document an argument that accepts multiple types, but I agree it's likely something people can infer. And now there's this issue to search for :)
